### ISSUE TITLE
Button or command:how to use

### ISSUE THREAD

**Issue by OilSubjectLoss7** [khaveesh/vim-fish-syntax#2]
How to use it?

**Comment by khaveesh** [comment]
This is a filetype plugin. It autoactivates if your file is a fish shell script based on the file extension or a shebang comment in the first line. Install this plugin the standard way you do with any other plugin. Use a plugin manager like https://github.com/savq/paq-nvim or git clone this repo to `~/.local/share/nvim/site/pack/packages/start`.
